### ISSUE TITLE
Using F10+W in Catacomb 3-D, level numbering is mistakenly started from 0

### ISSUE THREAD

**Issue by NY00123** [ArnoAnsems/CatacombGL#28]
The suggested range was originally "1-21". Currently, when you choose level no. x in the dialog within CatacombGL, you warp to the level that would otherwise be identified as x+1 in-game, even though it's technically x in the game data.

**Comment by ArnoAnsems** [comment]
Thanks for reporting this.
I've fixed this, such that the level numbering starts at 1 in the Catacomb 3-D warp cheat dialog. Since the numbers shown in CatacombGL are derived from the actual gamemaps content, it now shows "1-20".
It's funny how in the original source code (C3_DEBUG.C), the range is hard-coded to "1-21", but the subsequent if-statement dismisses 21. Maybe there was a test level at that spot during development?

`	else if (Keyboard[sc_W])	// W = warp to level
	{
		CenterWindow(26,3);
		PrintY+=6;
		US_Print("  Warp to which level(1-21):");
		VW_UpdateScreen();
		esc = !US_LineInput (px,py,str,NULL,true,2,0);
		if (!esc)
		{
			level = atoi (str);
			if (level>0 && level<21)
			{
				gamestate.mapon = level-1;
				playstate = ex_warped;
			}
		}
		return 1;
	}`

**Comment by ArnoAnsems** [comment]
I've included a fix in version 0.5.1.
