### ISSUE TITLE
Unlike the original ms-dos version

### ISSUE THREAD

**Issue by downmythroat753** [ArnoAnsems/CatacombGL#39]
Ok first thing that absolutely ruin *my* experience
Is the fact that i cant run or sprint because this game need sprint to avoid projectile and  long travel to get key and stuff. And the magic missile (or ball) that come out from my face, IT suppose to come out from my hand and it way too slow, The magic missile that in the original ms-dos version are way more faster and better They also come out from your hand which ultimately better, every times i look at the magic missile in the source port make me feel sick. Hopefully you will fix it and it will be the best source port ever. (Sorry if you not understand it, im not good at english and it grammar)

**Comment by ArnoAnsems** [comment]
Thanks for your feedback and reporting these issues!

It is possible to run in the source port, but you have to first assign a key to the "Run" action. Currently by default no key is assigned to "Run", since I was under the impression that none of the original Catacomb games had a run option. However, I just noticed that the original Catacomb 3D (The Descent) does have a run option. It is bound to the Right Shift key, so I will use that key as the default in the next update. There is currently also an "Always run" option, which is disabled by default.

It indeed appears as if the magic missile is coming out of the players' face. That will be fixed in the next update.

I compared the speed of the magic missile in CatacombGL with both DosBox and Reflection Keen. It does seem a bit slower in CatacombGL, but I don't think the difference in speed is more than 20%. I'm not sure what's causing the difference; it could be a round-off error.

**Comment by ArnoAnsems** [comment]
[CatacombGL 0.5.3](https://github.com/ArnoAnsems/CatacombGL/releases) is released,
As mentioned above, in this release the default run key is now Right Shift and the magic missiles are now spawned a bit further away from the player's face. I hope it helps.
