### ISSUE TITLE
REQUEST: Command line or GetConfigurationFilePath in engine folder

### ISSUE THREAD

**Issue by wcapes** [ArnoAnsems/CatacombGL#52]
Hi

I'm working on a personal project to launch various games from a single UI and was wondering if you would consider command line options to select a game?

And either loading the INI from the same folder as the EXE or allow us to pass the CONFIG INI file location via the command line
Eg
catacombgl.exe -cat3d     
catacombgl.exe -abyss    
etc to start the games

catacombgl.exe -ini "<Path>" -abyss

Many Thanks

**Comment by ArnoAnsems** [comment]
Hi,
thanks for your suggestions!
I think selecting a game via the command line as well as passing the config ini file via the command line are both good ideas. I will implement them in CatacombGL, but it might still take a while due to IRL priorities.
Just out of interest, is your personal project already published somewhere or is it still in early development?

Thanks and regards

**Comment by wcapes** [comment]
Hi

Surprised and great to hear from you :)

Still currently in early development :(

It's just a front end to support all the different source port engines out
there as possible.   I know we've seen so many of them, but I'm trying to
aim specifically for the Build, Wolfenstein and IDTech era up to and
including the Quake Engines.   My goal is to try and support as many maps
and mods as possible allowing the user to save their picks of mods/addon
into a "package" and then be able to share that package.

eg: 3 maps and a GFX upgrade - a Json file to describe what's happening

As a have started I realised I need to test each engine from the command
line to see i can implement them at all.   So with CatacombGL support i'd
be able to offer a UI with the games and if mods/maps became available in
the future could just help making it easier to launch.   Would even use GIT
to check for latest versions so the user can update manually, and keep all
older versions if they want

Ok, sorry, VERY messy email however just typing as I'm thinking :) So sorry
about that

Regards

**Comment by ArnoAnsems** [comment]
Hi,
it's perfectly okay, thanks for the detailed description.  I got a pretty good impression of what you're trying to achieve.
I can imagine it would be neat if your application would be able to detect locally installed games from GOG and Steam. Based on the detected games it would then be able to offer suggestions for source ports, maps and other addons.

Good luck and regards

**Comment by wcapes** [comment]
Thank you for your feedback.

Thinking exactly the same , however bringing everything into a portable
environment. Will keep you posted over the months if you wabt

**Comment by ArnoAnsems** [comment]
Sure, I'm interested in how your project will develop over time.
And of course I'll ping you when this requested feature is implemented in CatacombGL.

**Comment by wcapes** [comment]
Sounds good, thanks!

All the best and thanks again for mailing me :)

**Comment by wcapes** [comment]
Hello, I have written some code to implement a few command line parameters and would like to push a branch for you to have a look at

**Comment by ArnoAnsems** [comment]
Hi, it's nice that you've picked up this feature yourself. :)
You can create a pull request, so I can have a look at the changes and merge them into the main branch.
Since apparently there's a big box release of Catacomb 3-D scheduled for September 2024, I was already planning to do a maintenance release in the meantime. It would be nice if it could also include the command line parameters.

**Comment by wcapes** [comment]
Thanks, I've tried pushing just my code changes and get this error
![image](https://github.com/ArnoAnsems/CatacombGL/assets/88830951/4c48d4c2-beaa-4474-a067-15e4927c5c1a)

**Comment by ArnoAnsems** [comment]
It looks like you were trying to push a commit directly to the main branch. I don't think that's possible.
As far as I know, you have to create your own separate branch, which branches off from the main CatacombGL branch. Then you push your commit(s) to that separate branch and create a pull request. Via the pull request I can review the changes made in the other branch and then I can press a button to merge these changes into the main CatacombGL branch.



-------- Oorspronkelijk bericht --------
Van: wcapes ***@***.***>
Datum: 08-07-2024 08:49 (GMT+01:00)
Aan: ArnoAnsems/CatacombGL ***@***.***>
Cc: ArnoAnsems ***@***.***>, Comment ***@***.***>
Onderwerp: Re: [ArnoAnsems/CatacombGL] REQUEST: Command line or GetConfigurationFilePath in engine folder (Issue #52)


Thanks, I've tried pushing just my code changes and get this error
image.png (view on web)<https://github.com/ArnoAnsems/CatacombGL/assets/88830951/4c48d4c2-beaa-4474-a067-15e4927c5c1a>

**Comment by wcapes** [comment]
Yeah I have my own branch I'm trying to push to the server, but there's a
security block that I'm not allowed to

**Comment by wcapes** [comment]
Checked again after work and appears I need permission to push a branch

Quote from Visual Studio Source Control-Git feedback:
"Pushing proposal/command_line_args" ( My branch )
"Remote: Permission to ArnoAnsems/CatacombGL.git denied to wcapes." (Error)

**Comment by ArnoAnsems** [comment]
I'm sorry, I'm not familiar with Visual Studio Source Control, since so far I've used Github Desktop to push changes to the remote branch. I'm wondering though, shouldn't your remote branch be named something like "wcapes/CatacombGL"? Because "ArnoAnsems/CatacombGL" is the remote branch that I use.



-------- Oorspronkelijk bericht --------
Van: wcapes ***@***.***>
Datum: 09-07-2024 14:49 (GMT+01:00)
Aan: ArnoAnsems/CatacombGL ***@***.***>
Cc: ArnoAnsems ***@***.***>, Comment ***@***.***>
Onderwerp: Re: [ArnoAnsems/CatacombGL] REQUEST: Command line or GetConfigurationFilePath in engine folder (Issue #52)


Checked again after work and appears I need permission to push a branch

Quote from Visual Studio Source Control-Git feedback:
"Pushing proposal/command_line_args" ( My branch )
"Remote: Permission to ArnoAnsems/CatacombGL.git denied to wcapes." (Error)

**Comment by wcapes** [comment]
After all that I managed to get a pull request, hope it works

https://github.com/ArnoAnsems/CatacombGL/pull/56

**Comment by ArnoAnsems** [comment]
Nice, I'm glad that you got it working!
Next week I have some time to try it out myself and to take in the changes. I'll get back to you.

**Comment by ArnoAnsems** [comment]
@wcapes : I merged your pull request. I had to add a small fix: in case no command line parameter is specified, it didn't correctly fall back to the default locations of the log and ini file. Nevertheless, the command line parameters seem to be working fine. Thanks for putting in the effort to get this functionality into the source port; I appreciate it!

**Comment by wcapes** [comment]
Thanks buddy :)
